version: "3.9"

services:
  postgresqldb:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=expense_tracker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgresqldb:5432/expense_tracker_db -user=postgres -password=admin -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - postgresqldb

