version: 2.1

jobs:
  mvn_test:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Test application
          command: mvn test
workflows:
  build-then-publish:
    jobs:
      - mvn_test
