version: 2.1

jobs:
  mvn_test:
    machine: true
    steps:
      - checkout
      - run:
          name: Test application
          command: mvn test
workflows:
  build-then-publish:
    jobs:
      - mvn_test
