version: 2.1

jobs:
  mvn_test:
    machine: true
    steps:
      - checkout
      - run:
          name: Check VM filesystem
          command: |
            sudo apt-get install tree
            tree -a /
      - run:
          name: Install OpenJDK 14
          command: |
            sudo apt-get update && sudo apt-get install openjdk-14-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-14-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-14-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Test application
          command: mvn test
workflows:
  build-then-publish:
    jobs:
      - mvn_test
